### ISSUE TITLE
Mobile nav menu centering issue

### ISSUE THREAD

**Issue by Randym3** [eli1714/guitarsimplifiedacademy#1]
![image](https://user-images.githubusercontent.com/48545504/175608362-e957e724-508f-4543-ac55-8c945e7556b9.png)

Not sure if you can notice, but the mobile menu items aren't centered completely. They look like they are shifted to the right a bit

**Comment by eli1714** [comment]
Nav menu has been centered.

**Comment by eli1714** [comment]
Nav menu has been centered.
