### ISSUE TITLE
clean up html in hero section 

### ISSUE THREAD

**Issue by Randym3** [eli1714/guitarsimplifiedacademy#2]
https://github.com/eli1714/guitarsimplifiedacademy/blob/e97cb3fd3fd3eae730307748a2ca5969df8436bd/index.html#L35

Nothing wrong on the browser, but i'd wrap this section with a div. These are usually called "Hero sections"

so  i'd do

```
            <div clasas="hero_section"> 
                <h2 class="header-title">Guitar Simplified Academy</h2>
		<span class="sub-title">Learn Guitar Easily</span>
		<a class="btn btn-grow" href="#">Start Learning</a>
		<img class="guitar-pick-icon" src="img/guitar_pick_icon.svg" alt="Guitar Pick Icon">
            </div>
```

**Comment by eli1714** [comment]
Hero section is not needed since this section is formatted with the header.
