### ISSUE TITLE
Footer looks wonky

### ISSUE THREAD

**Issue by Randym3** [eli1714/guitarsimplifiedacademy#3]
![image](https://user-images.githubusercontent.com/48545504/175609310-b561b244-c56e-4ced-bac7-b56e25cc31ab.png)

looks weird. Make sure its all centered, and theres a nice amount of margins between them in mobile

**Comment by Randym3** [comment]
![image](https://user-images.githubusercontent.com/48545504/175609715-e59533ce-f23d-4be4-a20f-5615f69e7d41.png)

I made some changes to ".footer-list" added (width: 400px; text-align: center;)

also ".social-media-list" you should probably add "justify-content: center"

**Comment by eli1714** [comment]
Code has been updated.
