### ISSUE TITLE
fix javascript tags

### ISSUE THREAD

**Issue by Randym3** [eli1714/guitarsimplifiedacademy#5]
![image](https://user-images.githubusercontent.com/48545504/175610542-d12a9ac8-78c1-4d99-aaf4-acbabca0adf8.png)
Always make sure to have your javascript open and closing tags aligned.

Also, get in the habit of making a new JS file and including it in your html file, instead of having it all just on the HTML document

**Comment by eli1714** [comment]
Script code has been moved to an individual js file.
